### ISSUE TITLE
What's the font in README?

### ISSUE THREAD

**Issue by qu-way** [xero/figlet-fonts#11]
i.e. this one:
```
┏━╸╻┏━╸╻  ┏━╸╺┳╸   ┏━╸┏━┓┏┓╻╺┳╸┏━┓
┣╸ ┃┃╺┓┃  ┣╸  ┃    ┣╸ ┃ ┃┃┗┫ ┃ ┗━┓
╹  ╹┗━┛┗━╸┗━╸ ╹    ╹  ┗━┛╹ ╹ ╹ ┗━┛
```

**Comment by xero** [comment]
[future](https://github.com/xero/figlet-fonts/blob/master/future.tlf). i used a toilet font to write figlet semi-ironically.

**Comment by vba34520** [comment]
Thank you for your job!

I move the [future.tlf](https://github.com/xero/figlet-fonts/blob/master/future.tlf) to `usr/share/figlet`

Then
```shell
figlet -f future.tlf "FIGLET"
toilet -f future.tlf "FIGLET"
```

It raise
```
figlet: future: Unable to open font file
error: could not load font future.tlf
```

Could you please share your command?

**Comment by xero** [comment]
> I move the [future.tlf](https://github.com/xero/figlet-fonts/blob/master/future.tlf) to `usr/share/figlet`
> ```
> figlet: future: Unable to open font file
> error: could not load font future.tlf
> ```

you can use the info flag to show the correct directory for your installed version. 

the version installed from brew on a mac for instance is an odd place
```
> toilet -I 2
/usr/local/Cellar/toilet/0.3/share/figlet
```

you can also use the `-d` flag and pass the directory you want to your command. checkout the man pages of both program  for more details

**Comment by ShivamJoker** [comment]
Thanks!
