### ISSUE TITLE
Please add these fonts

### ISSUE THREAD

**Issue by ghost** [xero/figlet-fonts#21]
The site: http://patorjk.com/software/taag has these but I don't know how they could be obtained.

Abraxis-Big
Abraxis-Small
babyface-lame
babyface-leet
Bent
Blest
Boie
Boie2
Bone
CaMiZ
CeA
CeA2
Cheese
DaiR
Filth
FoGG
Galactus
Glue
Hellfire
HeX
MeDi
Mer
Patorjk
PsY
PsY2
Reeko Font 1
Ribbit
Ribbit2
Ribbit3
Sony
TRaC
TRaC Mini
TRaC Tiny
Twiggy
X99
X992
X-Pose
Zodi

**Comment by 4G3NT** [comment]
#!/bin/sh

fontDir="/usr/share/figlet"
toiletFlag=

help=$(
	cat << EOF
Usage:
$0 [-ht] [-d] [message]

OPTIONS
  -h	display this help
  -t	specify this option if you have toilet fonts aswell
  -d	font directory defaults to /usr/share/figlet
EOF
)

err()
{
	red="\033[31m"
	reset="\033[0m"
	for arg in "$@"; do
		printf "%berror%b: %s\n" "$red" "$reset" "$arg" >&2
	done
}

while getopts ":htd:" opt; do
	case "$opt" in
		h)
			printf "%s\n" "$help"
			exit
			;;
		t)
			toiletFlag=1
			;;
		d)
			fontDir="$OPTARG"
			[ -d "$fontDir" ] || {
				err "directory '$fontDir' does not exist"
				exit 2
			}
			;;
		:)
			err "option -$OPTARG requires an argument"
			exit 2
			;;
		*)
			err "invalid option -$OPTARG"
			exit 2
			;;
	esac
done

shift $((OPTIND - 1))

msg="$1"

[ -z "$msg" ] && {
	err "a message needs to be specified"
	exit 1
}

if [ -n "$toiletFlag" ]; then
	for i in "$fontDir"/*.flf "$fontDir"/*.tlf; do
		echo "Font: $(basename "$i" | sed 's#\.tlf##g;s#\.flf##g')"
		figlet -f "$i" "$msg"
	done
else
	for i in "$fontDir"/*.flf; do
		echo "Font: $(basename "$i" | sed 's#\.flf##g')"
		figlet -f "$i" "$msg"
	done
fi

**Comment by 4G3NT** [comment]
`#!/bin/sh

fontDir="/usr/share/figlet"
toiletFlag=

help=$(
	cat << EOF
Usage:
$0 [-ht] [-d] [message]

OPTIONS
  -h	display this help
  -t	specify this option if you have toilet fonts aswell
  -d	font directory defaults to /usr/share/figlet
EOF
)

err()
{
	red="\033[31m"
	reset="\033[0m"
	for arg in "$@"; do
		printf "%berror%b: %s\n" "$red" "$reset" "$arg" >&2
	done
}

while getopts ":htd:" opt; do
	case "$opt" in
		h)
			printf "%s\n" "$help"
			exit
			;;
		t)
			toiletFlag=1
			;;
		d)
			fontDir="$OPTARG"
			[ -d "$fontDir" ] || {
				err "directory '$fontDir' does not exist"
				exit 2
			}
			;;
		:)
			err "option -$OPTARG requires an argument"
			exit 2
			;;
		*)
			err "invalid option -$OPTARG"
			exit 2
			;;
	esac
done

shift $((OPTIND - 1))

msg="$1"

[ -z "$msg" ] && {
	err "a message needs to be specified"
	exit 1
}

if [ -n "$toiletFlag" ]; then
	for i in "$fontDir"/*.flf "$fontDir"/*.tlf; do
		echo "Font: $(basename "$i" | sed 's#\.tlf##g;s#\.flf##g')"
		figlet -f "$i" "$msg"
	done
else
	for i in "$fontDir"/*.flf; do
		echo "Font: $(basename "$i" | sed 's#\.flf##g')"
		figlet -f "$i" "$msg"
	done
fi`

**Comment by 4G3NT** [comment]
```
#!/bin/sh

fontDir="/usr/share/figlet"
toiletFlag=

help=$(
	cat << EOF
Usage:
$0 [-ht] [-d] [message]

OPTIONS
  -h	display this help
  -t	specify this option if you have toilet fonts aswell
  -d	font directory defaults to /usr/share/figlet
EOF
)

err()
{
	red="\033[31m"
	reset="\033[0m"
	for arg in "$@"; do
		printf "%berror%b: %s\n" "$red" "$reset" "$arg" >&2
	done
}

while getopts ":htd:" opt; do
	case "$opt" in
		h)
			printf "%s\n" "$help"
			exit
			;;
		t)
			toiletFlag=1
			;;
		d)
			fontDir="$OPTARG"
			[ -d "$fontDir" ] || {
				err "directory '$fontDir' does not exist"
				exit 2
			}
			;;
		:)
			err "option -$OPTARG requires an argument"
			exit 2
			;;
		*)
			err "invalid option -$OPTARG"
			exit 2
			;;
	esac
done

shift $((OPTIND - 1))

msg="$1"

[ -z "$msg" ] && {
	err "a message needs to be specified"
	exit 1
}

if [ -n "$toiletFlag" ]; then
	for i in "$fontDir"/*.flf "$fontDir"/*.tlf; do
		echo "Font: $(basename "$i" | sed 's#\.tlf##g;s#\.flf##g')"
		figlet -f "$i" "$msg"
	done
else
	for i in "$fontDir"/*.flf; do
		echo "Font: $(basename "$i" | sed 's#\.flf##g')"
		figlet -f "$i" "$msg"
	done
fi
```

**Comment by 4G3NT** [comment]
```sh
#!/bin/sh

fontDir="/usr/share/figlet"
toiletFlag=

help=$(
	cat << EOF
Usage:
$0 [-ht] [-d] [message]

OPTIONS
  -h	display this help
  -t	specify this option if you have toilet fonts aswell
  -d	font directory defaults to /usr/share/figlet
EOF
)

err()
{
	red="\033[31m"
	reset="\033[0m"
	for arg in "$@"; do
		printf "%berror%b: %s\n" "$red" "$reset" "$arg" >&2
	done
}

while getopts ":htd:" opt; do
	case "$opt" in
		h)
			printf "%s\n" "$help"
			exit
			;;
		t)
			toiletFlag=1
			;;
		d)
			fontDir="$OPTARG"
			[ -d "$fontDir" ] || {
				err "directory '$fontDir' does not exist"
				exit 2
			}
			;;
		:)
			err "option -$OPTARG requires an argument"
			exit 2
			;;
		*)
			err "invalid option -$OPTARG"
			exit 2
			;;
	esac
done

shift $((OPTIND - 1))

msg="$1"

[ -z "$msg" ] && {
	err "a message needs to be specified"
	exit 1
}

if [ -n "$toiletFlag" ]; then
	for i in "$fontDir"/*.flf "$fontDir"/*.tlf; do
		echo "Font: $(basename "$i" | sed 's#\.tlf##g;s#\.flf##g')"
		figlet -f "$i" "$msg"
	done
else
	for i in "$fontDir"/*.flf; do
		echo "Font: $(basename "$i" | sed 's#\.flf##g')"
		figlet -f "$i" "$msg"
	done
fi
```

**Comment by ghost** [comment]
I've emailed the website author, asking for the fonts, and I'm currently waiting for a reply.

**Comment by ghost** [comment]
Turns out these were AOL fonts which have no connection to figlet fonts and they only look good on Arial 10pt

**Comment by xero** [comment]
non-monospaced ascii is pretty rare. i appreciate you trying to track down more fonts ✌️
