### ISSUE TITLE
Some fonts dont have numbers

### ISSUE THREAD

**Issue by TLCPlusPlus** [xero/figlet-fonts#9]
Probably falling on deaf ears seeing how long it hasn't been updated in years, but here:

I noticed a issue while poking around some of the fonts.
I cant be bothered to list all of the fonts affected, but I know Bloody is affected.
So when I type in "foo12345bar"
It shows up as "foobar"

**Comment by xero** [comment]
this is my personal collection of fonts. a few of them were made by me, but most of them are by other authors. im not planning on modifying them to add more characters. sorry
